vm_spec = [
  {
    name: "rancher-step-01",
    cpu: 4,
    memory: 8192,
    private_ip: "192.168.3.11",
    storage: "100GB"
  },
  {
    name: "rancher-server-01",
    cpu: 4,
    memory: 8192,
    private_ip: "192.168.3.21",
    storage: "100GB"
  },
  {
    name: "rancher-controller-01",
    cpu: 4,
    memory: 8192,
    private_ip: "192.168.3.31",
    storage: "100GB"
  },
  {
    name: "rancher-worker-01",
    cpu: 4,
    memory: 8192,
    private_ip: "192.168.3.41",
    storage: "100GB"
  }
]

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.ssh.private_key_path = "~/.vagrant.d/insecure_private_key"

  vm_spec.each do |spec|
    config.vm.define spec[:name] do |server|
      server.vm.box = "generic/rocky8"
      server.vm.hostname = spec[:name]
      server.disksize.size = spec[:storage]
      server.vm.network :private_network, ip: spec[:private_ip]
      server.vm.provider "virtualbox" do | vbox |
        vbox.gui = false
        vbox.cpus = spec[:cpu]
        vbox.memory = spec[:memory]
      end
    end
  end
end
