---
- name: Install pip modules
  ansible.builtin.pip:
    name: requests
    state: present

- name: Deploy rancher containers
  community.general.docker_container:
    name: rancher
    image: rancher/rancher:{{ rancher.version }}
    ports:
      - 80:80
      - 443:443
    privileged: true
    restart_policy: unless-stopped
    state: started
