---
# docker run -d --restart=unless-stopped \
#   -p 80:80 -p 443:443 \
#   --privileged \
#   rancher/rancher:latest
- name: Deploy rancher containers
  community.general.docker_container:
    name: rancher
    image: rancher/rancher:{{ rancher.version }}
    ports:
      - 80:80
      - 443:443
    privileged: true
    restart_policy: unless-stopped
    state: started
