---
- name: Deploy rancher server
  hosts: rancher
  become: true
  roles:
    - name: common
      tags: common
    - name: geerlingguy.docker
      tags: docker
    - name: rancher
      tags: rancher
